spring:
  datasource:
  url: jdbc:h2:mem:sdw2025
  username: sdw2025
  password: 
jpa:
  show-sql: true
  open-in-view: false
  hibernate:
    ddl-auto: create #validate, update, create, create-drop
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      format_sql: true
      use_sql_comments: true
h2:
  console:
    enabled: true
    path: /h2-console
    settings:
      trace: false
      web-allow-others: false